doctor/urls.py
from django.urls import path

from .views import *

app_name = 'doctor'

urlpatterns = [
    path('create-update-availability', create_update_availability, name='create_update_availability'),
    path('availability-for-month', get_doctor_availability_for_month, name='doctor_availability_for_month'),
    path('appointments', AppointmentListView.as_view(), name='appointment_list'),
    path('prescription/core', core_template, name='prescription_template'),
    path('prescription/write', create_prescription, name='create_prescription'),
    path('vital/create', create_vital, name='create_vital'),
    path('diagnosis/create', create_diagnosis, name='create_diagnosis'),
]

healthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('patient/', include('patient.urls', namespace='patient')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('inventory.urls', namespace='inventory')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from web.views import *

app_name = 'web'

urlpatterns = [
    path('', HomePage.as_view(), name='home_page'),
    path('about', AboutPage.as_view(), name='about_page'),
    path('services', ServicePage.as_view(), name='service_page'),
    path('service<slug:slug>', ServiceDetailView.as_view(), name='service_detail'),
    path('contact', ContactPage.as_view(), name='contact_page'),
    path('appointment/new', create_appointment, name='create_appointment'),
    path('doctor/dates', load_available_date, name='load_available_date'),
    path('doctor/branches', load_doctor_branches, name='load_doctor_branches'),
    path('doctor/dates/slots', load_time_slot, name='load_time_slot'),
]

doctor/forms.py
from datetime import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit, Reset
from django import forms

from healthcare.utils import get_request, current_site
from patient.models import Patient
from user.models import Branch
from .models import Availability, Doctor, Appointment


class MonthAvailabilityForm(forms.Form):
    year = forms.IntegerField(initial=datetime.now().year, label='Year')
    month = forms.IntegerField(initial=datetime.now().month, label='Month')
    start_time = forms.TimeField()
    end_time = forms.TimeField()
    lunch_start_time = forms.TimeField(required=False)
    lunch_end_time = forms.TimeField(required=False)
    same_for_all_days = forms.BooleanField(required=False, label='Apply to all days of the month')


class AvailabilityForm(forms.ModelForm):
    class Meta:
        model = Availability
        fields = ['doctor', 'date', 'start_time', 'end_time', 'lunch_start_time', 'lunch_end_time', 'is_available']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'start_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
            'lunch_start_time': forms.TimeInput(attrs={'type': 'time'}),
            'lunch_end_time': forms.TimeInput(attrs={'type': 'time'}),
        }


class AppointmentForm(forms.ModelForm):
    doctor = forms.ModelChoiceField(
        queryset=Doctor.objects.none(),
        widget=forms.Select(
            attrs={
                'class': 'form-select bg-light border-0',
                'style': 'height: 55px;'
            }),
        label='')

    branch = forms.ModelChoiceField(
        queryset=Branch.objects.none(),
        widget=forms.Select(attrs={
            'class': 'form-select bg-light border-0',
            'style': 'height: 55px;'
        }), label='')

    date = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Date of appointment',
            'class': 'form-control bg-light border-0',
            'style': 'height: 55px;'
        }), label='')

    start_time = forms.CharField(
        widget=forms.Select(attrs={
            'placeholder': 'time of appointment',
            'class': 'form-select bg-light border-0',
            'style': 'height: 55px;'
        }), label='')

    class Meta:
        model = Appointment
        fields = ['doctor', 'branch', 'date', 'start_time']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['doctor'].queryset = Doctor.active_doctors()
        self.fields['branch'].queryset = Branch.all_branches()

        # Add empty option as a placeholder
        self.fields['doctor'].choices = [('', 'Select Doctor')] + list(self.fields['doctor'].choices)
        self.fields['branch'].choices = [('', 'Select Branch')] + list(self.fields['branch'].choices)

doctor/views.py
from django.template.loader import render_to_string

from diagnostics.models import Vital, Diagnosis
from medications.models import Prescription, PrescriptionDetail
from patient.models import Patient
import calendar
import sweetify
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView

from doctor.models import Availability, Appointment, Doctor
from healthcare.utils import month_name_to_number, get_dates_in_month, current_site
from medications.forms import PrescriptionForm, PrescriptionDetailForm, DiagnosisForm, VitalForm


class RelatedObjectDoesNotExist:
    pass


@login_required(login_url=reverse_lazy('user:login'))
def create_update_availability(request):
    doctor_id = request.GET.get('doctor_id')
    doctor = None
    try:
        if doctor_id:
            doctor = get_object_or_404(Doctor, pk=doctor_id)
        else:
            doctor = request.user.doctor
    except Exception as e:
        sweetify.warning(request, 'Restricted', text='You are not a doctor', persistent=True)
        return redirect(reverse_lazy('user:dashboard'))
    if request.method == 'POST':
        same_for_all_days = request.POST.get('same_for_all_days') == 'on'
        month_year = request.POST.get('month_year').split()
        # Convert month name to number
        month_name = month_year[0]
        year = int(month_year[1])
        month = month_name_to_number(month_name)

        if month is None:
            return JsonResponse({'status': 'error', 'errors': [{'date': '', 'error': 'Invalid month name.'}]},
                                status=400)

        # Get dates in the selected month
        days = get_dates_in_month(year, month)
        errors = []
        valid_data = []

        for day in days:
            is_available = request.POST.get(f'available_{day}') == 'on'
            start_time = request.POST.get(f'start_time_{day}')
            end_time = request.POST.get(f'end_time_{day}')
            lunch_start_time = request.POST.get(f'lunch_start_time_{day}')
            lunch_end_time = request.POST.get(f'lunch_end_time_{day}')

            if is_available:
                # Validate start and end times
                try:
                    if start_time and end_time and start_time >= end_time:
                        raise ValidationError(f"End time must be after start time.")
                    if lunch_start_time and lunch_end_time and lunch_start_time >= lunch_end_time:
                        raise ValidationError(f"Lunch end time must be after lunch start time.")
                except ValidationError as e:
                    errors.append({'date': day.strftime('%Y-%m-%d'), 'error': str(e)})
                    # Skip this date's data and continue with the next date
                    continue

                # Add to valid data if no errors
                try:
                    doctor_id = request.POST.get('doctor_id')
                    if doctor_id:
                        doctor = get_object_or_404(Doctor, pk=doctor_id)
                    else:
                        doctor = request.user.doctor
                except Exception as e:
                    pass

                valid_data.append({
                    'doctor': doctor,
                    'date': day,
                    'start_time': start_time,
                    'end_time': end_time,
                    'lunch_start_time': lunch_start_time,
                    'lunch_end_time': lunch_end_time,
                    'is_available': is_available
                })
        if errors:
            return JsonResponse({'status': 'error', 'errors': errors}, status=400)

        # Save valid data
        for data in valid_data:
            availability, created = Availability.objects.get_or_create(
                doctor=data['doctor'],
                date=data['date'],
                defaults={
                    'start_time': data['start_time'],
                    'end_time': data['end_time'],
                    'lunch_start_time': data['lunch_start_time'],
                    'lunch_end_time': data['lunch_end_time'],
                    'is_available': data['is_available'],
                    'organisation': current_site().organization,
                    'site': current_site(),
                    'branch_id': request.POST.get('branch')
                }
            )
            availability.start_time = data['start_time']
            availability.end_time = data['end_time']
            availability.lunch_start_time = data['lunch_start_time']
            availability.lunch_end_time = data['lunch_end_time']
            availability.is_available = data['is_available']
            availability.save()

        return JsonResponse({'status': 'success'}, status=200)
    return render(request, 'doctor/create_update_availability.html', {'doctor': doctor})


@login_required(login_url=reverse_lazy('user:login'))
def get_doctor_availability_for_month(request):
    if request.method == 'GET':
        month = int(request.GET.get('month'))
        year = int(request.GET.get('year'))
        doctor_id = request.GET.get('doctor_id')
        print('doctor_id: ', doctor_id)
        doctor = request.user.doctor
        if doctor_id:
            doctor = get_object_or_404(Doctor, pk=doctor_id)
        days_in_month = get_dates_in_month(year, month)  # Assuming this returns a list of date objects for the month
        availability_data = []

        for day in days_in_month:
            day_of_week = calendar.day_name[day.weekday()]  # Get the day of the week (e.g., 'Monday', 'Tuesday')
            availability = Availability.objects.filter(doctor=doctor, date=day).first()
            availability_data.append({
                'date': day.strftime('%Y-%m-%d'),
                'day_of_week': day_of_week,  # Add day of the week to the response
                'available': availability.is_available if availability else False,
                'start_time': availability.start_time.strftime(
                    '%H:%M') if availability and availability.start_time else '',
                'end_time': availability.end_time.strftime('%H:%M') if availability and availability.end_time else '',
                'lunch_start_time': availability.lunch_start_time.strftime(
                    '%H:%M') if availability and availability.lunch_start_time else '',
                'lunch_end_time': availability.lunch_end_time.strftime(
                    '%H:%M') if availability and availability.lunch_end_time else '',
            })

        return JsonResponse({'days': availability_data}, safe=False)


class AppointmentListView(ListView):
    model = Appointment
    queryset = Appointment.all()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return HttpResponseForbidden("Access Denied: Superusers only")  # ❌ Deny access

        return super().dispatch(request, *args, **kwargs)

def core_template(request):
    patient = Patient.objects.get(id='bb5bc46a-7ee2-40a6-913f-0c90af6a6d21')
    return render(request, 'medications/prescription_form.html', {'patient': patient})


def save_prescription_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            context = {}
            data['html_group_list'] = render_to_string('doctor/includes/_prescription_detail_list.html', context)
    else:
        data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    print(data)
    return JsonResponse(data)


def create_prescription(request):
    form = PrescriptionDetailForm()
    return save_prescription_form(request, form, 'doctor/includes/_prescription_detail_create.html')


def save_vital_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
    else:
        data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def save_diagnosis_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
    else:
        data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def create_vital(request):
    form = VitalForm()
    return save_vital_form(request, form, 'doctor/vital_create_form.html')


def create_diagnosis(request):
    form = DiagnosisForm()
    return save_diagnosis_form(request, form, 'doctor/vital_create_form.html')

doctor/templates/doctor/appointment_list.html
{% extends 'user/base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4">
            <span class="text-muted fw-light">Appointments /</span>List
        </h4>
        <div class="card">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="mb-0">Appointments</h5>
            </div>
            <div class="card-body">
                <div class="table">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>SN.</th>
                            <th>Patient</th>
                            <th>Age</th>
                            <th>Diagnosis</th>
                            <th>Prescription</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for appointment in object_list %}
                            <tr class="p-2">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ appointment.patient }}</td>
                                <td>{{ appointment.patient.age }}</td>
                                <td>NA</td>
                                <td><a href="" class="mr-2">view</a><a href="" class="ml-2">new</a></td>
                                <td><a href="">Done</a></td>
                            </tr>
                        {% empty %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

doctor/templates/doctor/create_update_availability.html
{% extends 'user/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4"><span
                class="text-muted fw-light">Appointment/</span> Availability/Change</h4>
        <!-- Basic Layout & Basic with Icons -->
        <div class="row">
            <!-- Basic Layout -->
            <div class="col-xxl">
                <div class="card">
                    <div class="card-body">
                        <form method="post" action="{% url 'doctor:create_update_availability' %}">
                            {% csrf_token %}
                            <input type="hidden" name="doctor_id" value="{{ doctor.pk }}" id="doctor_id">
                            <div class="form-group">
                                <label for="id_month_year">Month</label>
                                <input type="text" class="form-control" id="id_month_year" name="month_year"
                                       data-url="{% url 'doctor:doctor_availability_for_month' %}"/>
                            </div>
                            <!-- Apply to All Days Time Inputs -->
                            <div class="form-group row">

                <div class="col">
                    <label for="Branch">Branch</label>
                    <select class="choices form-select choices__input" data-choice="active" id="branch" name="branch" aria-label="Branch">
                        {% for branch in doctor.branches.all %}
                            <option value="{{ branch.pk }}">{{ branch.address }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col">
                    <label for="apply_start_time">Start Time</label>
                    <input type="time" class="form-control" id="apply_start_time" name="apply_start_time"
                           value="10:00"/>
                </div>
                <div class="col">
                    <label for="apply_end_time">End Time</label>
                    <input type="time" class="form-control" id="apply_end_time" name="apply_end_time" value="17:00"/>
                </div>
                <div class="col">
                    <label for="apply_lunch_start_time">Lunch Start Time</label>
                    <input type="time" class="form-control" id="apply_lunch_start_time" name="apply_lunch_start_time"
                           value="14:00"/>
                </div>
                <div class="col">
                    <label for="apply_lunch_end_time">Lunch End Time</label>
                    <input type="time" class="form-control" id="apply_lunch_end_time" name="apply_lunch_end_time"
                           value="15:00"/>
                </div>
                <div class="col">
                    <label class="mt-3"><input type="checkbox" id="apply_to_all" name="apply_to_all"/> Apply to All
                        Days</label>
                </div>
            </div>
                            <div class="mb-4">
                <h4>Daily Availability</h4>
                <table class="table table-bordered" id="availability-table">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Available</th>
                        <th>Start Time</th>
                        <th>End Time</th>
                        <th>Lunch Start Time</th>
                        <th>Lunch End Time</th>
                        <th>Error</th> <!-- Column for displaying errors -->
                    </tr>
                    </thead>
                    <tbody>
                    <!-- Data will be populated dynamically via JS -->
                    </tbody>
                </table>
            </div>
                            <button type="submit" class="btn btn-primary">Save Availability</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static 'doctor/js/availability.js' %}"></script>
{% endblock %}

doctor/templates/doctor/diagnosis_form.html
<form method="post" action="{% url 'doctor:create_prescription' %}" class="js-prescription-detail-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel5">Add Vitals</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {% include 'doctor/includes/_diagnosis_form.html' %}
    </div>s
    <div class="modal-footer">
        <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

doctor/templates/doctor/vital_create_form.html
<form method="post" action="{% url 'doctor:create_prescription' %}" class="js-prescription-detail-create-form">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel5">Add Vitals</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {% include 'doctor/includes/_vital_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>