doctor/urls.py
from django.urls import path

from .views import *

app_name = 'doctor'

urlpatterns = [
    path('create-update-availability', create_update_availability, name='create_update_availability'),
    path('availability-for-month', get_doctor_availability_for_month, name='doctor_availability_for_month'),
    path('appointments', AppointmentListView.as_view(), name='appointment_list'),
    path('prescription/core', core_template, name='prescription_template'),
    path('prescription/write', create_prescription, name='create_prescription'),
    path('vital/create', create_vital, name='create_vital'),
    path('diagnosis/create', create_diagnosis, name='create_diagnosis'),
]

healthcare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('patient/', include('patient.urls', namespace='patient')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('inventory.urls', namespace='inventory')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', CustomLogoutView.as_view(), name='logout'),
    path('', dashboard, name='dashboard'),
    path('list', UserListView.as_view(), name='users'),
    path('add', UserCreateView.as_view(), name='add_user'),
    path('update/<pk>', UserUpdateView.as_view(), name='update_user'),
    path('staff_attendance_report', staff_attendance_report, name='staff_attendance_report'),
    path('attendance/mark_out', mark_out, name='attendance_mark_out'),
    path('ip/add/whitelist', add_to_whitelist, name='add_to_whitelist'),
]

web/urls.py
from django.urls import path
from web.views import *

app_name = 'web'

urlpatterns = [
    path('', HomePage.as_view(), name='home_page'),
    path('about', AboutPage.as_view(), name='about_page'),
    path('services', ServicePage.as_view(), name='service_page'),
    path('service<slug:slug>', ServiceDetailView.as_view(), name='service_detail'),
    path('contact', ContactPage.as_view(), name='contact_page'),
    path('appointment/new', create_appointment, name='create_appointment'),
    path('doctor/dates', load_available_date, name='load_available_date'),
    path('doctor/branches', load_doctor_branches, name='load_doctor_branches'),
    path('doctor/dates/slots', load_time_slot, name='load_time_slot'),
]

doctor/forms.py
from datetime import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit, Reset
from django import forms

from healthcare.utils import get_request, current_site
from patient.models import Patient
from user.models import Branch
from .models import Availability, Doctor, Appointment


class MonthAvailabilityForm(forms.Form):
    year = forms.IntegerField(initial=datetime.now().year, label='Year')
    month = forms.IntegerField(initial=datetime.now().month, label='Month')
    start_time = forms.TimeField()
    end_time = forms.TimeField()
    lunch_start_time = forms.TimeField(required=False)
    lunch_end_time = forms.TimeField(required=False)
    same_for_all_days = forms.BooleanField(required=False, label='Apply to all days of the month')


class AvailabilityForm(forms.ModelForm):
    class Meta:
        model = Availability
        fields = ['doctor', 'date', 'start_time', 'end_time', 'lunch_start_time', 'lunch_end_time', 'is_available']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'start_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
            'lunch_start_time': forms.TimeInput(attrs={'type': 'time'}),
            'lunch_end_time': forms.TimeInput(attrs={'type': 'time'}),
        }


class AppointmentForm(forms.ModelForm):
    doctor = forms.ModelChoiceField(
        queryset=Doctor.objects.none(),
        widget=forms.Select(
            attrs={
                'class': 'form-select bg-light border-0',
                'style': 'height: 55px;'
            }),
        label='')

    branch = forms.ModelChoiceField(
        queryset=Branch.objects.none(),
        widget=forms.Select(attrs={
            'class': 'form-select bg-light border-0',
            'style': 'height: 55px;'
        }), label='')

    date = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Date of appointment',
            'class': 'form-control bg-light border-0',
            'style': 'height: 55px;'
        }), label='')

    start_time = forms.CharField(
        widget=forms.Select(attrs={
            'placeholder': 'time of appointment',
            'class': 'form-select bg-light border-0',
            'style': 'height: 55px;'
        }), label='')

    class Meta:
        model = Appointment
        fields = ['doctor', 'branch', 'date', 'start_time']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['doctor'].queryset = Doctor.active_doctors()
        self.fields['branch'].queryset = Branch.all_branches()

        # Add empty option as a placeholder
        self.fields['doctor'].choices = [('', 'Select Doctor')] + list(self.fields['doctor'].choices)
        self.fields['branch'].choices = [('', 'Select Branch')] + list(self.fields['branch'].choices)

doctor/views.py
from django.template.loader import render_to_string

from diagnostics.models import Vital, Diagnosis
from medications.models import Prescription, PrescriptionDetail
from patient.models import Patient
import calendar
import sweetify
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView

from doctor.models import Availability, Appointment, Doctor
from healthcare.utils import month_name_to_number, get_dates_in_month, current_site
from medications.forms import PrescriptionForm, PrescriptionDetailForm, DiagnosisForm, VitalForm


class RelatedObjectDoesNotExist:
    pass


@login_required(login_url=reverse_lazy('user:login'))
def create_update_availability(request):
    doctor_id = request.GET.get('doctor_id')
    doctor = None
    try:
        if doctor_id:
            doctor = get_object_or_404(Doctor, pk=doctor_id)
        else:
            doctor = request.user.doctor
    except Exception as e:
        sweetify.warning(request, 'Restricted', text='You are not a doctor', persistent=True)
        return redirect(reverse_lazy('user:dashboard'))
    if request.method == 'POST':
        same_for_all_days = request.POST.get('same_for_all_days') == 'on'
        month_year = request.POST.get('month_year').split()
        # Convert month name to number
        month_name = month_year[0]
        year = int(month_year[1])
        month = month_name_to_number(month_name)

        if month is None:
            return JsonResponse({'status': 'error', 'errors': [{'date': '', 'error': 'Invalid month name.'}]},
                                status=400)

        # Get dates in the selected month
        days = get_dates_in_month(year, month)
        errors = []
        valid_data = []

        for day in days:
            is_available = request.POST.get(f'available_{day}') == 'on'
            start_time = request.POST.get(f'start_time_{day}')
            end_time = request.POST.get(f'end_time_{day}')
            lunch_start_time = request.POST.get(f'lunch_start_time_{day}')
            lunch_end_time = request.POST.get(f'lunch_end_time_{day}')

            if is_available:
                # Validate start and end times
                try:
                    if start_time and end_time and start_time >= end_time:
                        raise ValidationError(f"End time must be after start time.")
                    if lunch_start_time and lunch_end_time and lunch_start_time >= lunch_end_time:
                        raise ValidationError(f"Lunch end time must be after lunch start time.")
                except ValidationError as e:
                    errors.append({'date': day.strftime('%Y-%m-%d'), 'error': str(e)})
                    # Skip this date's data and continue with the next date
                    continue

                # Add to valid data if no errors
                try:
                    doctor_id = request.POST.get('doctor_id')
                    if doctor_id:
                        doctor = get_object_or_404(Doctor, pk=doctor_id)
                    else:
                        doctor = request.user.doctor
                except Exception as e:
                    pass

                valid_data.append({
                    'doctor': doctor,
                    'date': day,
                    'start_time': start_time,
                    'end_time': end_time,
                    'lunch_start_time': lunch_start_time,
                    'lunch_end_time': lunch_end_time,
                    'is_available': is_available
                })
        if errors:
            return JsonResponse({'status': 'error', 'errors': errors}, status=400)

        # Save valid data
        for data in valid_data:
            availability, created = Availability.objects.get_or_create(
                doctor=data['doctor'],
                date=data['date'],
                defaults={
                    'start_time': data['start_time'],
                    'end_time': data['end_time'],
                    'lunch_start_time': data['lunch_start_time'],
                    'lunch_end_time': data['lunch_end_time'],
                    'is_available': data['is_available'],
                    'organisation': current_site().organization,
                    'site': current_site(),
                    'branch_id': request.POST.get('branch')
                }
            )
            availability.start_time = data['start_time']
            availability.end_time = data['end_time']
            availability.lunch_start_time = data['lunch_start_time']
            availability.lunch_end_time = data['lunch_end_time']
            availability.is_available = data['is_available']
            availability.save()

        return JsonResponse({'status': 'success'}, status=200)
    return render(request, 'doctor/create_update_availability.html', {'doctor': doctor})


@login_required(login_url=reverse_lazy('user:login'))
def get_doctor_availability_for_month(request):
    if request.method == 'GET':
        month = int(request.GET.get('month'))
        year = int(request.GET.get('year'))
        doctor_id = request.GET.get('doctor_id')
        print('doctor_id: ', doctor_id)
        doctor = request.user.doctor
        if doctor_id:
            doctor = get_object_or_404(Doctor, pk=doctor_id)
        days_in_month = get_dates_in_month(year, month)  # Assuming this returns a list of date objects for the month
        availability_data = []

        for day in days_in_month:
            day_of_week = calendar.day_name[day.weekday()]  # Get the day of the week (e.g., 'Monday', 'Tuesday')
            availability = Availability.objects.filter(doctor=doctor, date=day).first()
            availability_data.append({
                'date': day.strftime('%Y-%m-%d'),
                'day_of_week': day_of_week,  # Add day of the week to the response
                'available': availability.is_available if availability else False,
                'start_time': availability.start_time.strftime(
                    '%H:%M') if availability and availability.start_time else '',
                'end_time': availability.end_time.strftime('%H:%M') if availability and availability.end_time else '',
                'lunch_start_time': availability.lunch_start_time.strftime(
                    '%H:%M') if availability and availability.lunch_start_time else '',
                'lunch_end_time': availability.lunch_end_time.strftime(
                    '%H:%M') if availability and availability.lunch_end_time else '',
            })

        return JsonResponse({'days': availability_data}, safe=False)


class AppointmentListView(ListView):
    model = Appointment
    queryset = Appointment.all()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return HttpResponseForbidden("Access Denied: Superusers only")  # ❌ Deny access

        return super().dispatch(request, *args, **kwargs)

def core_template(request):
    patient = Patient.objects.get(id='bb5bc46a-7ee2-40a6-913f-0c90af6a6d21')
    return render(request, 'medications/prescription_form.html', {'patient': patient})


def save_prescription_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            context = {}
            data['html_group_list'] = render_to_string('doctor/includes/_prescription_detail_list.html', context)
    else:
        data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    print(data)
    return JsonResponse(data)


def create_prescription(request):
    form = PrescriptionDetailForm()
    return save_prescription_form(request, form, 'doctor/includes/_prescription_detail_create.html')


def save_vital_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
    else:
        data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def save_diagnosis_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
    else:
        data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def create_vital(request):
    form = VitalForm()
    return save_vital_form(request, form, 'doctor/vital_create_form.html')


def create_diagnosis(request):
    form = DiagnosisForm()
    return save_diagnosis_form(request, form, 'doctor/vital_create_form.html')

web/templates/web/base.html
{% load sweetify %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta %}{% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap"
          rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'web/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'web/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'web/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'web/lib/twentytwenty/twentytwenty.css' %}" rel="stylesheet"/>

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'web/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'web/css/style.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <style>
        .asteriskField {
            color: red;
            font-weight: bold;
        }
    </style>
    {% if form %}
        {{ form.media }}
    {% endif %}
    {% block style %}{% endblock %}
</head>
<body>

<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-grow text-primary m-1" role="status">
        <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-dark m-1" role="status">
        <span class="sr-only">Loading...</span>
    </div>
    <div class="spinner-grow text-secondary m-1" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->

<!-- Topbar Start -->
<div class="container-fluid bg-light ps-5 pe-0 d-none d-lg-block">
    <div class="row gx-0">
        <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
            <div class="owl-carousel owl-theme opening-hours-slider d-inline-flex align-items-center">
                {% for branch in branches %}
                    <div class="item">
                        <small class="py-2">
                            <i class="far fa-map text-primary me-2"></i>{{ branch.address }}<br>
                            <i class="far fa-clock text-primary me-2"></i>Opening Hours: {{ branch.opening_days }}
                            : {{ branch.opening_hours }}
                        </small>
                    </div>
                {% empty %}
                    <div class="item">
                        <small class="py-2"><i class="far fa-clock text-primary me-2"></i>Opening Hours: Wed - Fri :
                            7.00 am - 9.00 pm, Saturday Closed</small>
                    </div>
                    <div class="item">
                        <small class="py-2"><i class="far fa-clock text-primary me-2"></i>Opening Hours: Tue - Sun :
                            9.00 am - 5.00 pm, Monday Closed</small>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-6 text-center text-lg-end">
            <div class="position-relative d-inline-flex align-items-center bg-primary text-white top-shape px-5">
                <div class="me-3 pe-3 border-end py-2">
                    <p class="m-0"><i class="fa fa-envelope-open me-2"></i>{{ branches.first.email }}</p>
                </div>
                <div class="py-2">
                    <p class="m-0"><i class="fa fa-phone-alt me-2"></i>{{ branches.first.phone }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->

<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm px-5 py-3 py-lg-0">
    <a href="{% url 'web:home_page' %}" class="navbar-brand p-0">
        <img src="{% if org.logo %}{{ org.logo.url }}{% endif %}" style="width: 100px; height: 100px;">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto py-0">
            <a href="{% url 'web:home_page' %}" class="nav-item nav-link active">Home</a>
            <a href="{% url 'web:about_page' %}" class="nav-item nav-link">About</a>
            <a href="{% url 'web:service_page' %}" class="nav-item nav-link">Service</a>
            <a href="{% url 'web:contact_page' %}" class="nav-item nav-link">Contact</a>
            <a href="{% url 'user:login' %}" class="nav-item nav-link">Login</a>
        </div>
        <button type="button" class="btn text-dark" data-bs-toggle="modal" data-bs-target="#searchModal"><i
                class="fa fa-search"></i></button>
        <a href="{% url 'web:create_appointment' %}" class="btn btn-primary py-2 px-4 ms-3">Appointment</a>
    </div>
</nav>
<!-- Navbar End -->

<!-- Full Screen Search Start -->
<div class="modal fade" id="searchModal" tabindex="-1">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content" style="background: rgba(9, 30, 62, .7);">
            <div class="modal-header border-0">
                <button type="button" class="btn bg-white btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center justify-content-center">
                <div class="input-group" style="max-width: 600px;">
                    <input type="text" class="form-control bg-transparent border-primary p-3"
                           placeholder="Type search keyword">
                    <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Full Screen Search End -->

{% block content %}{% endblock %}

<!-- Newsletter Start -->
<div class="container-fluid position-relative pt-5 wow fadeInUp" data-wow-delay="0.1s" style="z-index: 1;">
    <div class="container">
        <div class="bg-primary p-5">
            <form class="mx-auto" style="max-width: 600px;">
                <div class="input-group">
                    <input type="text" class="form-control border-white p-3" placeholder="Your Email">
                    <button class="btn btn-dark px-4">Sign Up</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Newsletter End -->

<!-- Footer Start -->
<div class="container-fluid bg-dark text-light py-5 wow fadeInUp" data-wow-delay="0.3s" style="margin-top: -75px;">
    <div class="container pt-5">
        <div class="row g-5 pt-4">
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Quick Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-light mb-2" href="{% url 'web:home_page' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-light mb-2" href="{% url 'web:about_page' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-light mb-2" href="{% url 'web:service_page' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest
                        Blog</a>
                    <a class="text-light" href="{% url 'web:contact_page' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Popular Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-light mb-2" href="{% url 'web:home_page' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-light mb-2" href="{% url 'web:about_page' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-light mb-2" href="{% url 'web:contact_page' %}"><i
                            class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest
                        Blog</a>
                    <a class="text-light" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>{{ org.get_default_branch.address }}</p>
                <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>{{ org.get_default_branch.email }}
                </p>
                <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>{{ org.get_default_branch.phone }}</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Follow Us</h3>
                <div class="d-flex">
                    <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="#"><i
                            class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="#"><i
                            class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded me-2" href="#"><i
                            class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded" href="#"><i
                            class="fab fa-instagram fw-normal"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid text-light py-4" style="background: #051225;">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 text-center text-md-start">
                <p class="mb-md-0">&copy; <a class="text-white border-bottom" href="#">{{ org.name }}</a>. All Rights
                    Reserved.</p>
            </div>
            <div class="col-md-6 text-center text-md-end">
                <p class="mb-0">Designed by <a class="text-white border-bottom" href="https://htmlcodex.com">HTML
                    Codex</a><br>
                    Distributed by <a class="text-white border-bottom" href="https://themewagon.com">ThemeWagon</a>
                </p>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square rounded back-to-top"><i class="bi bi-arrow-up"></i></a>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<!-- Updated Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'web/lib/wow/wow.min.js' %}"></script>
<script src="{% static 'web/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'web/lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'web/lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'web/lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'web/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'web/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'web/lib/twentytwenty/jquery.event.move.js' %}"></script>
<script src="{% static 'web/lib/twentytwenty/jquery.twentytwenty.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'web/js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
{% sweetify %}
{% block script %}{% endblock %}
</body>
</html>

web/templates/web/service.html
{% extends  'web/base.html' %}
{% load static %}
{% block title %}Home Page{% endblock %}
{% block meta %}{% endblock %}
{% block content %}

    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Services</h1>
                <a href="" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="" class="h4 text-white">Services</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Service Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5 mb-5">
                <div class="section-title mb-5">
                    <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Services</h5>
                    <h1 class="display-5 mb-0">We Offer The Best Quality Treatment Services</h1>
                </div>
                <!-- Department Navigation Bar -->
                <ul class="nav nav-pills mb-3" id="departmentTabs">
                    <li class="nav-item">
                        <a class="nav-link {% if request.GET.department == None %}active{% endif %}" href="{% url 'web:service_page' %}">All</a>
                    </li>
                    {% for department in departments %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.GET.department == department.name %}active{% endif %}" href="{% url 'web:service_page' %}?department={{ department.name }}">{{ department }}</a>
                        </li>
                    {% endfor %}
                    <!-- Add more departments as needed -->
                </ul>
                <div class="row g-3">
                    {% for service in services %}
                        <div class="col-md-4 service-item wow zoomIn" data-wow-delay="0.6s">
                            <div class="rounded-top overflow-hidden">
                                <img class="img-fluid" src="{% if service.image %}{{ service.image.url }}{% else %}{% static 'web/img/service-1.jpg' %}{% endif %}"
                                     alt="" style="width: 100%; height: 300px;">
                            </div>
                            <div class="position-relative bg-light rounded-bottom text-center p-4">
                                <h5 class="m-0">{{ service }}</h5>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Service End -->
{% endblock %}